WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 1280
VIRTUAL_HEIGHT = 720

SQUARE_SIZE = 30

GRID_WIDTH_SQUARES = 14
GRID_HEIGHT_SQUARES = 22

GRID_WIDTH = GRID_WIDTH_SQUARES * SQUARE_SIZE
GRID_HEIGHT = GRID_HEIGHT_SQUARES * SQUARE_SIZE

START_X = GRID_WIDTH_SQUARES / 2
START_Y = 1